### ISSUE TITLE
seems like some export options are broken for notebooks

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/scipy-binder#24]
- [x] export as pdf when using lab view.  notebook was opened (older execution) and export attempted without executing again

![image](https://user-images.githubusercontent.com/13630233/128618361-d62f8e73-b94b-4b74-b479-ff9d9f199fd9.png)

**Comment by ambarb** [comment]
html works, I did not try the others

**Comment by mpmdean** [comment]
@ambarb I consider this fixed on the beta JupyterHub. Should we close this?

**Comment by ambarb** [comment]
@mpmdean thank you for your effort on this.  Exporting as PDF doesn't handle markdown tables very well that have a lot of text, but this is probably a lower level problem.  I am comfortable closing this since having tons of text in a markdown table is an edge use case.  Feel free to re-open if you think that is needed.
